"""On-demand FSS sensitivity sweep across (α, β) settings (v5 Decision 12).

Run from the repo root:

    python scripts/fss_sensitivity.py runs/<run_id>                  # 4-tier sweep
    python scripts/fss_sensitivity.py runs/<run_id> --alpha 1 --beta 1   # single point

Reads the run's manifest + per-model DBs the same way `run_analysis` does,
but invokes only `accuracy.fss(...)` per (model, α, β) pair. Writes
`runs/<run_id>/analysis/fss_sensitivity.csv` with columns:
`model / alpha / beta / fss / fss_pe_mean / n_valid_questions`.

This script is **not** part of `run_analysis`. Reviewers querying
"why (α, β) = (2, 0.5)?" run it once on demand and read the CSV; the
main `per_model_summary.csv` always reports the (2, 0.5) FSS without
sweep clutter.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from forecast_eval import db as dbmod  # noqa: E402
from forecast_eval.analysis.accuracy import fss  # noqa: E402
from forecast_eval.analysis.flatten import _answer_gt_for, _flatten_db  # noqa: E402


# Default 4-tier sweep matching plan §1.10 / Decision 12:
#   (1, 1)   Jaccard / symmetric
#   (1, 0.5) mild asymmetry
#   (2, 0.5) v5 default — published main-table value
#   (3, 0.5) strict asymmetry — multi-selection error costs 6× missed
DEFAULT_TIERS: list[tuple[float, float]] = [
    (1.0, 1.0),
    (1.0, 0.5),
    (2.0, 0.5),
    (3.0, 0.5),
]


def _load_samples_and_gt(
    run_dir: Path,
) -> tuple[dict[str, list], dict[str, frozenset[str]]]:
    """Read manifest + per-model DBs, return (samples_by_model, gt_map)."""
    manifest = json.loads((run_dir / "manifest.json").read_text(encoding="utf-8"))
    models: list[str] = manifest["models"]
    model_files: dict[str, str] = manifest["model_files"]
    sampling_n_top: int = manifest.get("sampling_n", 1)
    db_dir = run_dir / "db"

    samples_by_model: dict[str, list] = {}
    gt_map_global: dict[str, frozenset[str]] = {}

    for model in models:
        db_path = db_dir / model_files[model]
        if not db_path.exists():
            continue
        conn = dbmod.connect(db_path)
        try:
            meta_row = conn.execute(
                "SELECT sampling_n FROM run_meta ORDER BY started_at DESC LIMIT 1"
            ).fetchone()
            sampling_n = int(meta_row["sampling_n"]) if meta_row else sampling_n_top
            samples_by_model[model] = _flatten_db(conn, sampling_n, model)
            for qid, gt in _answer_gt_for(conn).items():
                gt_map_global.setdefault(qid, gt)
        finally:
            conn.close()

    return samples_by_model, gt_map_global


def _resolve_tiers(args: argparse.Namespace) -> list[tuple[float, float]]:
    """Pick the (α, β) sweep set from CLI args.

    `--all` (default when no `--alpha` / `--beta` given) → 4-tier sweep.
    `--alpha A --beta B` → single point.
    """
    if args.alpha is not None and args.beta is not None:
        return [(args.alpha, args.beta)]
    return list(DEFAULT_TIERS)


def run_sensitivity(
    run_dir: Path,
    *,
    tiers: list[tuple[float, float]] | None = None,
) -> Path:
    """Compute FSS for each (model, (α, β)) and write the sensitivity CSV.

    Returns the written CSV path. The CSV has a comment line on top
    explaining its provenance (Decision 12: not part of run_analysis).
    """
    if tiers is None:
        tiers = list(DEFAULT_TIERS)
    samples_by_model, gt_map = _load_samples_and_gt(run_dir)

    analysis_dir = run_dir / "analysis"
    analysis_dir.mkdir(parents=True, exist_ok=True)
    out_path = analysis_dir / "fss_sensitivity.csv"

    rows: list[list] = []
    for model in sorted(samples_by_model.keys()):
        samples = samples_by_model[model]
        for alpha, beta in tiers:
            result = fss(samples, gt_map, alpha=alpha, beta=beta)
            rows.append([
                model,
                alpha,
                beta,
                _fmt(result["fss"]),
                _fmt(result["mean_pe"]),
                result["n_valid"],
            ])

    with out_path.open("w", newline="", encoding="utf-8") as f:
        # Provenance comment so a reviewer reading the bare CSV knows this
        # is NOT a `run_analysis` artefact.
        f.write(
            "# Generated by scripts/fss_sensitivity.py — NOT part of run_analysis output.\n"
            "# Sweep across (α, β) settings on a single run; default published metric uses (2, 0.5).\n"
        )
        writer = csv.writer(f)
        writer.writerow([
            "model", "alpha", "beta",
            "fss", "fss_pe_mean", "n_valid_questions",
        ])
        writer.writerows(rows)
    return out_path


def _fmt(v: float | None, digits: int = 6) -> str:
    if v is None:
        return ""
    return f"{round(v, digits)}"


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="FSS sensitivity sweep (v5 Decision 12). "
                    "Writes runs/<id>/analysis/fss_sensitivity.csv."
    )
    p.add_argument(
        "run_dir",
        type=Path,
        help="Path to runs/<run_id> (the directory containing manifest.json).",
    )
    p.add_argument(
        "--alpha", type=float, default=None,
        help="Tversky α (FP weight). Requires --beta. Default: sweep 4 tiers.",
    )
    p.add_argument(
        "--beta", type=float, default=None,
        help="Tversky β (FN weight). Requires --alpha.",
    )
    p.add_argument(
        "--all", action="store_true",
        help="Explicitly request the 4-tier sweep (overrides --alpha/--beta).",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if args.all:
        tiers = list(DEFAULT_TIERS)
    elif (args.alpha is None) != (args.beta is None):
        print(
            "fss_sensitivity: --alpha and --beta must be passed together.",
            file=sys.stderr,
        )
        return 2
    else:
        tiers = _resolve_tiers(args)

    if not args.run_dir.is_dir():
        print(f"fss_sensitivity: {args.run_dir} is not a directory.", file=sys.stderr)
        return 2
    if not (args.run_dir / "manifest.json").exists():
        print(
            f"fss_sensitivity: {args.run_dir}/manifest.json missing.",
            file=sys.stderr,
        )
        return 2

    out = run_sensitivity(args.run_dir, tiers=tiers)
    print(f"Wrote {out} ({len(tiers)} (α, β) tier(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
